### ISSUE TITLE
Add a  possibility to have a beta/dev channel of the app to disribute it for testing

### ISSUE THREAD

**Issue by nanu-c** [UbuntuOpenStore/openstore-meta#167] opened 2018-01-01 21:37 UTC
In the gapps you can join individually for some apps to a beta testing.
This is a nice to have for app development.

**Comment by bhdouglass** [comment] 2018-01-02 05:36
Thanks for the suggestion, I'm closing this because it's a duplicate of #141.

**Closed by bhdouglass** 2018-01-02 05:36 UTC
