### ISSUE TITLE
Let UBports (or other organizations) reserve one or more namespaces for future Apps

### ISSUE THREAD

**Issue by Flohack74** [UbuntuOpenStore/openstore-meta#135] opened 2017-08-04 21:19 UTC
There was the idea to "protect" certain namespaces from being uploaded into openstore in order that no one can take over and distribute malicious/unwanted content in the name of a core App. What do you think?

**Comment by sverzegnassi** [comment] 2017-08-04 22:45
com.ubuntu.* and com.ubports.* seem to be already protected. See https://github.com/UbuntuOpenStore/openstore-web/blob/75ffef0163218a2a49b7ae7af723f47635c4c6fd/api/app/apps.js#L409

Currently, only trusted users or admins can upload apps with a reserved namespace. Looking at the list of people with such privilege, it seems already reasonable to me. Do you think we should enhance the policy any further?

**Comment by bhdouglass** [comment] 2017-08-04 23:44
Duplicate of one you already make @Flohack74 ;)
https://github.com/UbuntuOpenStore/openstore-meta/issues/124

**Closed by bhdouglass** 2017-08-04 23:44 UTC

**Comment by Flohack74** [comment] 2017-08-05 07:24
Ok the story was:

- I remembered that we talked about it
- I searched open bugs and did not find it
- I searched our conversation and concluded I forgot to do the ticket 🗡 

Thats life with butracking xD
